### PR TITLE
Add Portuguese translations

### PR DESCRIPTION
**Pull request by ViPeR5000**

### CODE REVIEW

**Comment by ViPeR5000** [comment]
We have 

pt-PT portuguese from Portugal
And
pt-BR portuguese from Brazil

**Comment by robbinjanssen** [comment]
I know but as you can see [here](https://github.com/home-assistant/frontend/blob/master/src/translations/translationMetadata.json#L134-L139), home assistant looks for `pt.json` ;)

**Comment by ViPeR5000** [comment]
> I know but as you can see [here](https://github.com/home-assistant/frontend/blob/master/src/translations/translationMetadata.json#L134-L139), home assistant looks for `pt.json` ;)



You can rename the filé  :)

**Comment by robbinjanssen** [comment]
Released in v1.1.2 :) thanks for your contribution!

**Pull request merged**
